/**
 * @file images.h
 * @brief Image resource table generated by WCHGUIDesigner.
 * @note Byte order: Big Endian
 */

#ifndef _IMAGES_H_
#define _IMAGES_H_

#include <stdint.h>
#include <stddef.h>

typedef enum {
    IMAGE_NONE = 0xFFFF,
    // === Raw images (0b000) ===
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0030 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 0),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0031 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 1),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0032 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 2),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0033 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 3),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0034 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 4),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0035 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 5),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0036 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 6),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0037 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 7),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0038 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 8),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0039 = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 9),
    IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_003A = MAKE_IMAGE_ID(IMAGE_TYPE_RAW, 10),
    // === CLUT images (0b010) ===
    IMAGE_RES_IMG_TPL_MAIN_PAGELIGHTCFG1 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 11),
    IMAGE_RES_IMG_TPL_MAIN_PAGELIGHTCFG2 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 12),
    IMAGE_RES_IMG_TPL_MAIN_PAGELIGHTCOLOR1 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 13),
    IMAGE_RES_IMG_TPL_MAIN_PAGELIGHTCOLOR2 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 14),
    IMAGE_RES_IMG_TPL_MAIN_PAGERELDATA1 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 15),
    IMAGE_RES_IMG_TPL_MAIN_PAGERELDATA2 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 16),
    IMAGE_RES_IMG_TPL_MAIN_PAGEANIMAL1 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 17),
    IMAGE_RES_IMG_TPL_MAIN_PAGEANIMAL2 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 18),
    IMAGE_RES_IMG_TPL_MAIN_PAGEMODEL1 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 19),
    IMAGE_RES_IMG_TPL_MAIN_PAGEMODEL2 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 20),
    IMAGE_RES_IMG_TPL_MAIN_PAGESETTING1 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 21),
    IMAGE_RES_IMG_TPL_MAIN_PAGESETTING2 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 22),
    IMAGE_RES_IMG_TPL_MAIN_BAT00 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 23),
    IMAGE_RES_IMG_TPL_MAIN_BAT01 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 24),
    IMAGE_RES_IMG_TPL_MAIN_BAT02 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 25),
    IMAGE_RES_IMG_TPL_MAIN_BAT03 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 26),
    IMAGE_RES_IMG_TPL_MAIN_BAT04 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 27),
    IMAGE_RES_IMG_TPL_MAIN_BAT05 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 28),
    IMAGE_RES_IMG_TPL_MAIN_BAT06 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 29),
    IMAGE_RES_IMG_TPL_MAIN_BAT07 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 30),
    IMAGE_RES_IMG_TPL_MAIN_BAT08 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 31),
    IMAGE_RES_IMG_TPL_MAIN_BAT09 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 32),
    IMAGE_RES_IMG_TPL_MAIN_BAT10 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 33),
    IMAGE_RES_IMG_TPL_MAIN_BAT11 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 34),
    IMAGE_RES_IMG_TPL_MAIN_BAT12 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 35),
    IMAGE_RES_IMG_TPL_MAIN_BAT13 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 36),
    IMAGE_RES_IMG_TPL_MAIN_BAT14 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 37),
    IMAGE_RES_IMG_TPL_MAIN_BAT15 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 38),
    IMAGE_RES_IMG_TPL_MAIN_BAT16 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 39),
    IMAGE_RES_IMG_TPL_MAIN_BAT17 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 40),
    IMAGE_RES_IMG_TPL_MAIN_BAT18 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 41),
    IMAGE_RES_IMG_TPL_MAIN_BAT19 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 42),
    IMAGE_RES_IMG_TPL_MAIN_BAT20 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 43),
    IMAGE_RES_IMG_TPL_MAIN_BAT21 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 44),
    IMAGE_RES_IMG_TPL_MAIN_CON1 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 45),
    IMAGE_RES_IMG_TPL_MAIN_CON2 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 46),
    IMAGE_RES_IMG_TPL_MAIN_CON3 = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 47),
    IMAGE_RES_IMG_TPL_MAIN_BG = MAKE_IMAGE_ID(IMAGE_TYPE_CLUT, 48),
} image_index_t;

static const image_info_t image_table[] = {
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0030
        .addr      = 0x0001DED4,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0031
        .addr      = 0x0001E0DC,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0032
        .addr      = 0x0001E2E4,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0033
        .addr      = 0x0001E4EC,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0034
        .addr      = 0x0001E6F4,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0035
        .addr      = 0x0001E8FC,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0036
        .addr      = 0x0001EB04,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0037
        .addr      = 0x0001ED0C,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0038
        .addr      = 0x0001EF14,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_0039
        .addr      = 0x0001F11C,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_ART_WUI_PAGE_MAIN_MAIN_TIME_003A
        .addr      = 0x0001F324,
        .width     = 10,
        .height    = 26,
        .data_size = 520,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGELIGHTCFG1
        .addr      = 0x00000000,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGELIGHTCFG2
        .addr      = 0x00001E3C,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGELIGHTCOLOR1
        .addr      = 0x00003C78,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGELIGHTCOLOR2
        .addr      = 0x00005AB4,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGERELDATA1
        .addr      = 0x000078F0,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGERELDATA2
        .addr      = 0x0000972C,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGEANIMAL1
        .addr      = 0x0000B568,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGEANIMAL2
        .addr      = 0x0000D3A4,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGEMODEL1
        .addr      = 0x0000F1E0,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGEMODEL2
        .addr      = 0x0001101C,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGESETTING1
        .addr      = 0x00012E58,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_PAGESETTING2
        .addr      = 0x00014C94,
        .width     = 73,
        .height    = 99,
        .data_size = 7739,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT00
        .addr      = 0x00016AD0,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT01
        .addr      = 0x00016F74,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT02
        .addr      = 0x00017418,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT03
        .addr      = 0x000178BC,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT04
        .addr      = 0x00017D60,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT05
        .addr      = 0x00018204,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT06
        .addr      = 0x000186A8,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT07
        .addr      = 0x00018B4C,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT08
        .addr      = 0x00018FF0,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT09
        .addr      = 0x00019494,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT10
        .addr      = 0x00019938,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT11
        .addr      = 0x00019DDC,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT12
        .addr      = 0x0001A280,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT13
        .addr      = 0x0001A724,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT14
        .addr      = 0x0001ABC8,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT15
        .addr      = 0x0001B06C,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT16
        .addr      = 0x0001B510,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT17
        .addr      = 0x0001B9B4,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT18
        .addr      = 0x0001BE58,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT19
        .addr      = 0x0001C2FC,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT20
        .addr      = 0x0001C7A0,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BAT21
        .addr      = 0x0001CC44,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_CON1
        .addr      = 0x0001D0E8,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_CON2
        .addr      = 0x0001D58C,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_CON3
        .addr      = 0x0001DA30,
        .width     = 26,
        .height    = 26,
        .data_size = 1188,
    },
    {  // IMAGE_RES_IMG_TPL_MAIN_BG
        .addr      = 0x0001F52C,
        .width     = 320,
        .height    = 240,
        .data_size = 77312,
    },
};

#define RAW_IMAGE_COUNT   11
#define RLE_IMAGE_COUNT   0
#define CLUT_IMAGE_COUNT  38
#define CLUT4_IMAGE_COUNT 0
#define IMAGE_COUNT       49

static inline const image_info_t* get_image(image_index_t index) {
    uint16_t idx = IMAGE_GET_INDEX(index);
    if (idx >= IMAGE_COUNT) return NULL;
    return &image_table[idx];
}

#endif /* _IMAGES_H_ */
